# Generated by Django 2.2.5 on 2020-03-12 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200311_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 13, 43, 23, 188442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='valores_conceptos',
            name='id_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Formulario'),
        ),
    ]
