# Generated by Django 2.2.5 on 2020-03-27 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200312_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 6, 45, 50, 963079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
