# Generated by Django 2.2.5 on 2020-03-27 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200327_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 6, 56, 15, 529940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='valores_conceptos',
            name='id_formulario',
            field=models.IntegerField(),
        ),
    ]
