# Generated by Django 2.2.5 on 2020-03-27 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20200327_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 7, 37, 38, 484721, tzinfo=utc)),
        ),
    ]
